# ML Assigment

Vuyo Ncume 2095458 <br/>
Vhugala Mudau 2094007 <br/>
Amatullah Mthethwa 1870175 <br/>
Melissa Mmatshaka 2111308 <br/>
Rumbidzai Moyo 1856080

In [17]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from sklearn.metrics import confusion_matrix

### The data:

In [18]:
d = pd.read_csv('heart_failure_clinical_records_dataset.csv')

# dropping missing values if there are any
data = d.dropna().copy()

data.head()

age  anaemia  creatinine_phosphokinase  diabetes  ejection_fraction  \
0  75.0        0                       582         0                 20   
1  55.0        0                      7861         0                 38   
2  65.0        0                       146         0                 20   
3  50.0        1                       111         0                 20   
4  65.0        1                       160         1                 20   

   high_blood_pressure  platelets  serum_creatinine  serum_sodium  sex  \
0                    1  265000.00               1.9           130    1   
1                    0  263358.03               1.1           136    1   
2                    0  162000.00               1.3           129    1   
3                    0  210000.00               1.9           137    1   
4                    0  327000.00               2.7           116    0   

   smoking  time  DEATH_EVENT  
0        0     4            1  
1        0     6            1  
2        1     7            1  
3        0     7            1  
4        0     8            1

### Splitting into training, validation and testing data

Note: 60% of the data is for training, 20% for validation and the rest for testing.

In [19]:
training_data = data.loc[0:179,]
training_data.tail()

age  anaemia  creatinine_phosphokinase  diabetes  ejection_fraction  \
175  60.0        1                        95         0                 60   
176  69.0        0                      1419         0                 40   
177  49.0        1                        69         0                 50   
178  63.0        1                       122         1                 60   
179  55.0        0                       835         0                 40   

     high_blood_pressure  platelets  serum_creatinine  serum_sodium  sex  \
175                    0   337000.0               1.0           138    1   
176                    0   105000.0               1.0           135    1   
177                    0   132000.0               1.0           140    0   
178                    0   267000.0               1.2           145    1   
179                    0   279000.0               0.7           140    1   

     smoking  time  DEATH_EVENT  
175        1   146            0  
176        1   147            0  
177        0   147            0  
178        0   147            0  
179        1   147            0

In [20]:
validation_data = data.loc[180:239,]
validation_data.tail()

age  anaemia  creatinine_phosphokinase  diabetes  ejection_fraction  \
235  77.0        1                       109         0                 50   
236  75.0        0                       119         0                 50   
237  70.0        0                       232         0                 30   
238  65.0        1                       720         1                 40   
239  55.0        1                       180         0                 45   

     high_blood_pressure  platelets  serum_creatinine  serum_sodium  sex  \
235                    1  406000.00              1.10           137    1   
236                    1  248000.00              1.10           148    1   
237                    0  173000.00              1.20           132    1   
238                    0  257000.00              1.00           136    0   
239                    0  263358.03              1.18           137    1   

     smoking  time  DEATH_EVENT  
235        0   209            0  
236        0   209            0  
237        0   210            0  
238        0   210            0  
239        1   211            0

In [21]:
testing_data = data.loc[240:298,]
testing_data.tail()

age  anaemia  creatinine_phosphokinase  diabetes  ejection_fraction  \
294  62.0        0                        61         1                 38   
295  55.0        0                      1820         0                 38   
296  45.0        0                      2060         1                 60   
297  45.0        0                      2413         0                 38   
298  50.0        0                       196         0                 45   

     high_blood_pressure  platelets  serum_creatinine  serum_sodium  sex  \
294                    1   155000.0               1.1           143    1   
295                    0   270000.0               1.2           139    0   
296                    0   742000.0               0.8           138    0   
297                    0   140000.0               1.4           140    1   
298                    0   395000.0               1.6           136    1   

     smoking  time  DEATH_EVENT  
294        1   270            0  
295        0   271            0  
296        0   278            0  
297        1   280            0  
298        1   285            0

## The Decision Tree Algorithm

In [22]:
from DecisionTree import Node

In [23]:
# Defining the X and Y matrices
Y = training_data['DEATH_EVENT'].values
X = training_data[['age', 'anaemia', 'diabetes', 'high_blood_pressure', 'smoking']]

# validation and test data
Y_validate = validation_data['DEATH_EVENT'].values
X_validate = validation_data[['age', 'anaemia', 'diabetes', 'high_blood_pressure', 'smoking']]
Y_test = testing_data['DEATH_EVENT'].values
X_test = testing_data[['age', 'anaemia', 'diabetes', 'high_blood_pressure', 'smoking']]

# Saving the feature list 
features = list(X.columns)

In [24]:
# define the dictionary of hyperparameters
hp = {
 'max_depth': 3,
 'min_samples_split': 50
}

In [25]:
# algorithm setup
root = Node(Y, X, **hp)

# train algorithm
root.grow_tree()

In [10]:
# print tree structure
root.print_tree()

Root
   | Gain: 0.49
   | Class distribution in the node: {1: 80, 0: 100}
   | Predicted class: 0
|-------- Split rule: age <= 67.5
           | Gain: 0.44
           | Class distribution in the node: {1: 41, 0: 82}
           | Predicted class: 0
|---------------- Split rule: age <= 60.5
                   | Gain: 0.46
                   | Class distribution in the node: {1: 34, 0: 59}
                   | Predicted class: 0
|------------------------ Split rule: diabetes <= 0.5
                           | Gain: 0.42
                           | Class distribution in the node: {1: 16, 0: 37}
                           | Predicted class: 0
|------------------------ Split rule: diabetes > 0.5
                           | Gain: 0.49
                           | Class distribution in the node: {1: 18, 0: 22}
                           | Predicted class: 0
|---------------- Split rule: age > 60.5
                   | Gain: 0.36
                   | Class distribution in the node: {1: 7, 0:

In [26]:
# make prediction on training data
prediction = root.predict(X)
result = confusion_matrix(Y, prediction)
print('after training: \n', result)
print('accuracy: ', (result[0,0]+result[1,1])/len(Y)*100,'%')

after training: 
 [[82 18]
 [41 39]]
accuracy:  67.22222222222223 %


In [27]:
# make prediction on validation data
prediction = root.predict(X_validate)
result = confusion_matrix(Y_validate, prediction)
print('validation: \n', result)
print('accuracy: ', (result[0,0]+result[1,1])/len(Y_validate)*100,'%')

validation: 
 [[31 16]
 [10  3]]
accuracy:  56.666666666666664 %


In [28]:
# finding best hyperparameters
hp = {
 'max_depth': 4,
 'min_samples_split': 50
}

In [29]:
# validating with new hyperparameters
new_root = Node(Y, X, **hp)
new_root.grow_tree()
new_root.print_tree()
prediction = new_root.predict(X_validate)
result = confusion_matrix(Y_validate, prediction)
print('optimising hyperparameters: \n', result)
print('accuracy: ', (result[0,0]+result[1,1])/len(Y_validate)*100,'%')

Root
   | Gain: 0.49
   | Class distribution in the node: {1: 80, 0: 100}
   | Predicted class: 0
|-------- Split rule: age <= 67.5
           | Gain: 0.44
           | Class distribution in the node: {1: 41, 0: 82}
           | Predicted class: 0
|---------------- Split rule: age <= 60.5
                   | Gain: 0.46
                   | Class distribution in the node: {1: 34, 0: 59}
                   | Predicted class: 0
|------------------------ Split rule: diabetes <= 0.5
                           | Gain: 0.42
                           | Class distribution in the node: {1: 16, 0: 37}
                           | Predicted class: 0
|-------------------------------- Split rule: smoking <= 0.5
                                   | Gain: 0.48
                                   | Class distribution in the node: {1: 13, 0: 20}
                                   | Predicted class: 0
|-------------------------------- Split rule: smoking > 0.5
                                   | Gain: 

In [30]:
# Final accuracy on model
prediction = new_root.predict(X_test)
result = confusion_matrix(Y_test, prediction)
print('final results: \n', result)
print('accuracy: ', (result[0,0]+result[1,1])/len(Y_test)*100,'%')

final results: 
 [[47  9]
 [ 3  0]]
accuracy:  79.66101694915254 %
